<?php

$data = [
    'delivery' => [
        'prefix' => 'D',
        'headers' => [
            'アイテム名',
            '必要数',
            '準備数',
        ],
        'items' => [
            ['name' => '油紙', 'count' => 50, 'itemId' => 7151],
            ['name' => 'なめらかな紙', 'count' => 50, 'itemId' => 7111],
            ['name' => 'とてもかたい桃', 'count' => 50, 'itemId' => 7164],
            ['name' => '黒い熊の皮', 'count' => 50, 'itemId' => 7161],
            ['name' => '葉っぱの服', 'count' => 50, 'itemId' => 7298],
            ['name' => 'バンブーバスケット', 'count' => 50, 'itemId' => 7299],
            ['name' => '乾いた砂', 'count' => 50, 'itemId' => 7264],
            ['name' => '龍の歯', 'count' => 50, 'itemId' => 7266],
            ['name' => 'ドケビの角', 'count' => 50, 'itemId' => 1021],
            ['name' => 'ハーピーの羽', 'count' => 50, 'itemId' => 7115],
            ['name' => '極楽鳥の羽', 'count' => 50, 'itemId' => 6405],
            ['name' => 'デワタドラゴンの皮', 'count' => 50, 'itemId' => 6403],
            ['name' => 'ババヤガのきね', 'count' => 50, 'itemId' => 7762],
            ['name' => '歌う草', 'count' => 50, 'itemId' => 707],
            ['name' => 'ジェジェゼロピー', 'count' => 50, 'itemId' => 6498],
            ['name' => '清楚な花', 'count' => 50, 'itemId' => 6510],
            ['name' => '偽装缶詰', 'count' => 30, 'itemId' => 6426],
            ['name' => 'ひとくちケーキ', 'count' => 25, 'itemId' => 539],
            ['name' => 'よく焼いたクッキー', 'count' => 25, 'itemId' => 538],
            ['name' => '穴が開いている靴下', 'count' => 10, 'itemId' => 7034],
            ['name' => 'プレゼントボックス', 'count' => 10, 'itemId' => 644],
            ['name' => '魂が宿った宝石', 'count' => 25, 'itemId' => 25298],
            ['name' => '雪玉', 'count' => 25, 'itemId' => 25299],
            ['name' => '微かな夢の欠片', 'count' => 50, 'itemId' => 25256],
            ['name' => '血の付いた恋文', 'count' => 50, 'itemId' => 25257],
            ['name' => '短い蝙蝠の毛', 'count' => 15, 'itemId' => 25263],
            ['name' => '悪夢の塊', 'count' => 15, 'itemId' => 25264],
            ['name' => '黒い魂の欠片', 'count' => 15, 'itemId' => 25311],
            ['name' => '古い甲羅', 'count' => 25, 'itemId' => 25313],
            ['name' => 'ベアロピー', 'count' => 25, 'itemId' => 11620],
            ['name' => 'ネジリアンのソウルストーン', 'count' => 10, 'itemId' => 25615],
            ['name' => '堅く固まった泥', 'count' => 15, 'itemId' => 25641],
            ['name' => '古のウータンファイターの毛', 'count' => 15, 'itemId' => 25635],
            ['name' => '虹色のゼリーの欠片', 'count' => 60, 'itemId' => 25778],
            ['name' => '謎の樹液', 'count' => 60, 'itemId' => 25777],
        ],
    ],
    'subjugation' => [
        'prefix' => 'S',
        'headers' => [
            'モンスター名',
            '討伐数',
            '出現地',
        ],
        'items' => [
            ['name' => 'クリスタル(黄)', 'count' => 5, 'spawn' => ''],
            ['name' => 'クリスタル(緑)', 'count' => 5, 'spawn' => ''],
            ['name' => 'クリスタル(赤)', 'count' => 5, 'spawn' => ''],
            ['name' => 'クリスタル(青)', 'count' => 5, 'spawn' => ''],
            ['name' => 'アンソニ', 'count' => 5, 'spawn' => ''],
            ['name' => 'ジャッククリスマス', 'count' => 10, 'spawn' => ''],
            ['name' => 'クリスマスゴブリン', 'count' => 10, 'spawn' => ''],
            ['name' => 'サンタオーク', 'count' => 10, 'spawn' => ''],
            ['name' => 'サンタポリン', 'count' => 10, 'spawn' => ''],
            ['name' => 'サンタスモーキー', 'count' => 10, 'spawn' => ''],
            ['name' => '靴下スモーキー', 'count' => 10, 'spawn' => ''],
            ['name' => 'ターキーペコ', 'count' => 15, 'spawn' => ''],
            ['name' => 'クリスマスクッキー', 'count' => 10, 'spawn' => ''],
            ['name' => 'ミストケース', 'count' => 10, 'spawn' => ''],
            ['name' => '突撃赤バジルリスク', 'count' => 50, 'spawn' => ''],
            ['name' => '突撃緑バジルリスク', 'count' => 50, 'spawn' => ''],
            ['name' => 'ペル', 'count' => 5, 'spawn' => ''],
            ['name' => 'スイングペル', 'count' => 4, 'spawn' => ''],
            ['name' => '狂暴な警備犬', 'count' => 4, 'spawn' => ''],
            ['name' => '古代のバトン', 'count' => 3, 'spawn' => ''],
            ['name' => '深海のカナトウス', 'count' => 3, 'spawn' => ''],
            ['name' => '深海のカニ', 'count' => 3, 'spawn' => ''],
            ['name' => 'ミニオン(DI)(中級)', 'count' => 5, 'spawn' => ''],
            ['name' => 'ミニオン(カーリッツ)(中級)', 'count' => 5, 'spawn' => ''],
            ['name' => 'fff・ジターバグ', 'count' => 1, 'spawn' => ''],
            ['name' => 'おもちゃ工場警備兵', 'count' => 5, 'spawn' => ''],
            ['name' => '梱包されたボックス', 'count' => 5, 'spawn' => ''],
            ['name' => '大長老アイリン', 'count' => 1, 'spawn' => ''],
            ['name' => '落ちた白の騎士', 'count' => 5, 'spawn' => ''],
            ['name' => '腐敗した兵士', 'count' => 35, 'spawn' => ''],
            ['name' => 'アムダライス', 'count' => 1, 'spawn' => ''],
            ['name' => 'ラウンドライダー', 'count' => 30, 'spawn' => ''],
            ['name' => 'サイドライダー', 'count' => 30, 'spawn' => ''],
            ['name' => 'ブレードライダー', 'count' => 30, 'spawn' => ''],
            ['name' => '死神アンク', 'count' => 1, 'spawn' => ''],
            ['name' => '死者のオークゾンビ', 'count' => 15, 'spawn' => ''],
            ['name' => '死者のベリット', 'count' => 15, 'spawn' => ''],
            ['name' => '死神のメガロドン', 'count' => 15, 'spawn' => ''],
            ['name' => 'モルス・ネクロマンサー', 'count' => 1, 'spawn' => ''],
            ['name' => 'モルス・魔導士', 'count' => 1, 'spawn' => ''],
            ['name' => 'ビジョウ', 'count' => 1, 'spawn' => ''],
            ['name' => 'パワフルスケルトン', 'count' => 1, 'spawn' => ''],
            ['name' => 'パワフルSスケルトン', 'count' => 1, 'spawn' => ''],
            ['name' => 'パワフルAスケルトン', 'count' => 1, 'spawn' => ''],
            ['name' => 'S・J・アーネストウルフ', 'count' => 1, 'spawn' => ''],
            ['name' => '不死のウィンドゴースト', 'count' => 1, 'spawn' => ''],
            ['name' => '不死の呪われた騎士', 'count' => 1, 'spawn' => ''],
            ['name' => '不死のゾンビ', 'count' => 50, 'spawn' => ''],
            ['name' => 'タフィー', 'count' => 15, 'spawn' => ''],
            ['name' => 'フローズンウルフ', 'count' => 15, 'spawn' => ''],
            ['name' => 'T_W_O', 'count' => 1, 'spawn' => ''],
            ['name' => 'セリーヌ・キミ', 'count' => 1, 'spawn' => ''],
            ['name' => '暴虐のシーラカンス', 'count' => 1, 'spawn' => ''],
            ['name' => '変異のシーラカンス', 'count' => 1, 'spawn' => ''],
            ['name' => '真化カトリーヌ(上級)', 'count' => 1, 'spawn' => ''],
            ['name' => '真化マーガレッタ(上級)', 'count' => 1, 'spawn' => ''],
            ['name' => '怨恨の兵士', 'count' => 10, 'spawn' => ''],
            ['name' => '怨恨の弓兵', 'count' => 10, 'spawn' => ''],
            ['name' => '魔眼のアムダライス', 'count' => 1, 'spawn' => ''],
            ['name' => 'トップラウンドライダー', 'count' => 5, 'spawn' => ''],
            ['name' => 'トップサイドライダー', 'count' => 5, 'spawn' => ''],
            ['name' => 'トップブレードライダー', 'count' => 5, 'spawn' => ''],
            ['name' => 'ハートハンターBC', 'count' => 10, 'spawn' => ''],
            ['name' => 'ハートハンターFW', 'count' => 10, 'spawn' => ''],
            ['name' => 'イーブル', 'count' => 1, 'spawn' => ''],
            ['name' => 'ハートハンター警備兵', 'count' => 10, 'spawn' => ''],
            ['name' => 'Y.S.F.0.1 セイレン', 'count' => 1, 'spawn' => ''],
            ['name' => '無名のアーチャー', 'count' => 1, 'spawn' => ''],
            ['name' => '無名のマーチャント', 'count' => 1, 'spawn' => ''],
            ['name' => 'ハートハンター・ベラレ(CP)', 'count' => 1, 'spawn' => ''],
            ['name' => 'ツイン・カプトゥ(CP)', 'count' => 1, 'spawn' => ''],
            ['name' => 'ドロール(CP)', 'count' => 1, 'spawn' => ''],
            ['name' => 'ミグエル', 'count' => 1, 'spawn' => ''],
            ['name' => 'メイドの思念', 'count' => 10, 'spawn' => ''],
            ['name' => '女騎士の思念', 'count' => 7, 'spawn' => ''],
            ['name' => '白騎士の思念', 'count' => 7, 'spawn' => ''],
            ['name' => '呪いを飲み込んだ王', 'count' => 1, 'spawn' => ''],
            ['name' => '汚染されたレイドリック', 'count' => 5, 'spawn' => ''],
            ['name' => '汚染されたスティング', 'count' => 5, 'spawn' => ''],
            ['name' => '硬化ラヴァーゴーレム', 'count' => 5, 'spawn' => ''],
            ['name' => '硬化ナイトメアテラー', 'count' => 5, 'spawn' => ''],
            ['name' => '怒りのアイスタイタン', 'count' => 5, 'spawn' => ''],
            ['name' => '怒りのスノーウアー', 'count' => 5, 'spawn' => ''],
            ['name' => '怒りの九尾狐', 'count' => 5, 'spawn' => ''],
            ['name' => '怨恨のソヒー', 'count' => 5, 'spawn' => ''],
            ['name' => 'スウィートナイトメア', 'count' => 5, 'spawn' => ''],
            ['name' => 'マットドレインリアー', 'count' => 5, 'spawn' => ''],
            ['name' => '不吉なアサルトタートル', 'count' => 5, 'spawn' => ''],
            ['name' => '不吉なPタートル', 'count' => 5, 'spawn' => ''],
            ['name' => '白色のベアドール', 'count' => 5, 'spawn' => ''],
            ['name' => '赤色のベアドール', 'count' => 5, 'spawn' => ''],
            ['name' => '古のメガリス', 'count' => 5, 'spawn' => ''],
            ['name' => '古のフレイムシューター', 'count' => 5, 'spawn' => ''],
            ['name' => '混沌のポポリン', 'count' => 5, 'spawn' => ''],
            ['name' => '混沌のバフォメット.Jr', 'count' => 5, 'spawn' => ''],
            ['name' => 'フェンリル', 'count' => 1, 'spawn' => ''],
            ['name' => 'サラの幻影', 'count' => 1, 'spawn' => ''],
            ['name' => 'ダークフェイスワーム', 'count' => 3, 'spawn' => ''],
            ['name' => '暴走した船長ペルロック', 'count' => 1, 'spawn' => ''],
            ['name' => '魔神の使徒・アハト', 'count' => 1, 'spawn' => ''],
            ['name' => '魔神の使徒・シナイム', 'count' => 1, 'spawn' => ''],
            ['name' => 'セイレン=ウィンザー', 'count' => 5, 'spawn' => ''],
            ['name' => 'マーガレッタ=ソリン', 'count' => 5, 'spawn' => ''],
            ['name' => 'セリア=アルデ', 'count' => 5, 'spawn' => ''],
            ['name' => 'エミュール=プラメール', 'count' => 5, 'spawn' => ''],
            ['name' => 'EL-A17T', 'count' => 1, 'spawn' => ''],
            ['name' => '無名のソードマン', 'count' => 1, 'spawn' => ''],
        ]
    ],
    'quest' => [
        'prefix' => 'Q',
        'headers' => [
            'クエスト名',
            '石スキップ',
        ],
        'items' => [
            ['name' => 'The Sign 1部', 'skip' => 60],
            ['name' => 'The Sign 2部', 'skip' => 40],
            ['name' => 'The Sign 3部', 'skip' => 20],
            ['name' => 'アユタヤダンジョン', 'skip' => 15],
            ['name' => '消えた住人とバコナワ', 'skip' => 20],
            ['name' => 'キル・ハイル', 'skip' => 55],
            ['name' => 'クジラ島を訪ねて', 'skip' => 40],
            ['name' => '七王家とユミルの心臓', 'skip' => 100],
            ['name' => 'ジャティ族の王冠', 'skip' => 25],
            ['name' => '修道院クエスト', 'skip' => 30],
            ['name' => '新任看護師と病院', 'skip' => 25],
            ['name' => '聖域の秘密', 'skip' => 15],
            ['name' => '生体工場研究所侵入', 'skip' => 25],
            ['name' => '地下遺跡アドベンチャー', 'skip' => 50],
            ['name' => '通行手形クエスト', 'skip' => 15],
            ['name' => 'トイレのオバケ', 'skip' => 10],
            ['name' => 'トール火山の秘密', 'skip' => 50],
            ['name' => 'ファンタスマゴリカ', 'skip' => 40],
            ['name' => '月刊ブリガン', 'skip' => false],
            ['name' => 'フレイムヴァレーへの道', 'skip' => 10],
            ['name' => 'プロンテラ地下水路', 'skip' => 1],
            ['name' => '宝石クエスト', 'skip' => 10],
            ['name' => '森の中の秘密', 'skip' => 30],
            ['name' => '楽園団', 'skip' => 1],
            ['name' => '歴史学者', 'skip' => 45],
            ['name' => 'レゲンシュルム研究所', 'skip' => 20],
            ['name' => 'レッケンベル社の噂', 'skip' => 30],
            ['name' => 'ロックリッジ', 'skip' => 25],
            ['name' => '異世界', 'skip' => 5],
            ['name' => 'テラグローリア', 'skip' => 100],
            ['name' => '双子の真実', 'skip' => false],
            ['name' => '隊長の贖罪', 'skip' => false],
            ['name' => 'イルシオン', 'skip' => false],
            ['name' => 'パトリックを探して', 'skip' => false],
            ['name' => '燃料補給', 'skip' => false],
            ['name' => '魔術', 'skip' => false],
            ['name' => '料理作成', 'skip' => false],
            ['name' => 'スパイ疑惑', 'skip' => false],
            ['name' => 'Z団', 'skip' => false],
            ['name' => '不吉な噂', 'skip' => false],
            ['name' => 'ウィグナー家の心の箱', 'skip' => false],
            ['name' => 'レベンブルク家の絆', 'skip' => false],
            ['name' => 'バルター家の調査', 'skip' => false],
            ['name' => '至極の宴会料理', 'skip' => false],
            ['name' => '吟遊詩人', 'skip' => false],
            ['name' => 'ヘリオン', 'skip' => false],
            ['name' => '隠された財宝', 'skip' => false],
            ['name' => '破滅のダイヤモンド', 'skip' => false],
            ['name' => '不運のエメラルド', 'skip' => false],
            ['name' => '大神官', 'skip' => false],
            ['name' => '運命のカラス', 'skip' => false],
            ['name' => 'タートルアイランド', 'skip' => 1],
            ['name' => 'アルベルタの少年', 'skip' => false],
            ['name' => '借金返済', 'skip' => false],
            ['name' => '恋人', 'skip' => false],
            ['name' => '工場', 'skip' => false],
            ['name' => 'シドクス', 'skip' => false],
            ['name' => '通行証', 'skip' => false],
            ['name' => 'レッケンベル運送', 'skip' => false],
            ['name' => '婚約者探し', 'skip' => false],
            ['name' => '父親探し', 'skip' => false],
            ['name' => '思い出の木', 'skip' => false],
            ['name' => '駐屯地の人々', 'skip' => 10],
            ['name' => '会議のおとも', 'skip' => 15],
            ['name' => '生態研究', 'skip' => false],
            ['name' => '魔王モロク追跡', 'skip' => false],
            ['name' => '三ヶ国への報告書', 'skip' => 40],
            ['name' => '知恵の王の指輪', 'skip' => 15],
            ['name' => 'エルディカティス', 'skip' => 25],
            ['name' => '猫耳と尻尾の男', 'skip' => 30],
            ['name' => 'ビフロスト', 'skip' => false],
            ['name' => 'マヌクのモンスター討伐', 'skip' => false],
            ['name' => '二つの種族', 'skip' => 35],
            ['name' => '紫色の竜', 'skip' => false],
            ['name' => '友達のために', 'skip' => false],
            ['name' => 'モーラの温泉調査', 'skip' => false],
            ['name' => 'ロペの捜索', 'skip' => false],
            ['name' => '地元騎士団〜霧の森〜', 'skip' => false],
            ['name' => '冒険者達との出会い', 'skip' => false],
            ['name' => '塔の中の冒険者〜記念品収集〜', 'skip' => false],
            ['name' => '美しさの代償', 'skip' => false],
            ['name' => 'エクラージュの王', 'skip' => false],
            ['name' => '悠久なる絆', 'skip' => false],
            ['name' => '滅亡祝福教団', 'skip' => false],
            ['name' => 'モモタロ体験館', 'skip' => false],
            ['name' => '闘技場', 'skip' => false],
            ['name' => '高台', 'skip' => false],
            ['name' => '言語習得', 'skip' => 1],
            ['name' => 'ガラナ', 'skip' => false],
            ['name' => 'デワタの伝統酒', 'skip' => false],
            ['name' => '鉄人料理長ニャスの伝説', 'skip' => false],
            ['name' => '飛行船第1部', 'skip' => false],
            ['name' => '飛行船第2部', 'skip' => false],
            ['name' => 'オーディン神殿発掘団', 'skip' => false],
            ['name' => '大統領 第1部', 'skip' => false],
            ['name' => '大統領 第2部', 'skip' => false],
            ['name' => '黒い石', 'skip' => false],
            ['name' => '名前はアサヒ', 'skip' => false],
            ['name' => '月夜花の悪夢', 'skip' => false],
            ['name' => 'フローズンメモリー', 'skip' => false],
            ['name' => '魔法使いのノート', 'skip' => false],
            ['name' => '陽居村の幽霊少女', 'skip' => false],
            ['name' => 'ネジリアン帝国の陰謀', 'skip' => false],
            ['name' => 'ルワンダに伝える話', 'skip' => false],
            ['name' => '新人アコライトの幽霊', 'skip' => false],
        ]
    ],
];

header('Content-Type: application/json');
echo json_encode($data);
